### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by SoxIn4** [danielbrodin/atom-open-in#4]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/More/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/user/.atom/packages/open-in/lib/open-in.coffee:8:9)
```

**Comment by danielbrodin** [comment]
Deprecations have been fixed in latest release.
